Make the default XPath version implementation defined
xproc/3.0-specification pull request #1092
Opened 2024-04-14 17:40 UTC by ndw

Closes issue 39 in the vnext repository.

2024-04-14 18:28 UTC, gimsieke requested changes
minor typo

2024-04-14 18:28 UTC, gimsieke commented on xproc/src/main/xml/specification.xml
> +use the same version for all pipelines. <impl>If an implementation elects to us the
us → use

2024-04-15 05:24 UTC, xml-project commented
I think this is a good solution for the inheritance problem. But I am not sure how it covers the problem when the pipeline is asking for an XPath version not supported by the processor. Does this PR suggest the reaction as implementation-defined?

2024-04-15 06:29 UTC, ndw commented
Fixed the typo. Extended `err:XS0110` to cover versions less than 3.1 or other versions unsupported by the processor.

2024-04-15 06:36 UTC, gimsieke approved these changes

2024-06-06 10:42 UTC, merged