Attempt to clarify p:import-functions
xproc/3.0-specification pull request #1111
Opened 2024-08-28 17:18 UTC by ndw

Fix #1110

2024-08-28 19:36 UTC, gimsieke approved these changes

2024-08-29 06:00 UTC, xml-project requested changes
I am sorry to disagree with one aspect, but I think that functions imported in a p:library should not be automatically visible in a pipeline importing that library. As far as I can see, this break the current scoping rules for import.
If I want to use a function in a step, a p:import-function should be necessary to avoid scoping problems in the importing step.

2024-08-29 08:30 UTC, ndw commented
Yes. I think you're absolutely right. I did note in the issue that I wasn't sure what the right answer was. Thanks for telling me :-)

2024-08-29 14:25 UTC, xml-project commented
@ndw 

> I did note in the issue that I wasn't sure what the right answer was.

Sorry, I missed that question.

2024-08-29 14:38 UTC, merged